#!/bin/bash
export VAULT_ADDR='https://vault.originrose.com:8200'

echo "Requesting AWS creds..."
creds=`vault read secret/legend/aws/core`
access_key=$(echo "$creds" | awk '/access_key/ { print $2 }')
secret_key=$(echo "$creds" | awk '/secret_key/ { print $2 }')

export AWS_ACCESS_KEY_ID=$access_key
export AWS_SECRET_ACCESS_KEY=$secret_key
export AWS_SESSION_TOKEN=""
