#!/bin/bash
script_dir=$(dirname $0)

err_report() {
  echo "errexit on line $(caller)" >&2
}

trap err_report ERR
source $script_dir/getkey.sh
ssh -i "$credfile" -A $user@$host "cd legend-analytics && \
  git commit -a -m 'lab updates' && \
  git pull --rebase origin master"
rm ${credfile}
